language: java
install: ./mvnw install -DskipTests=true -Dgpg.skip=true
script: mvn verify javadoc:javadoc site:site

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7
  - openjdk6


